# -*- coding: utf-8 -*-
"""Midterm_Project_Predict_Customer_Churn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EDBs-fJ-HOZspb_3V3Uqyd2He-zQLaud
"""

import kagglehub

# Download dataset
path = kagglehub.dataset_download(
    "mohankrishnathalla/predict-customer-churn-submission-dataset"
)

print("Dataset path:", path)

import os

files = os.listdir(path)
print(files)

import pandas as pd

# Read the Origin.csv file from the downloaded path
df = pd.read_csv(f"{path}/Original.csv")

# Check the dataset shape (number of rows and columns)
print("Shape:", df.shape)

# Display the first few rows of the dataset
print(df.head())

# Convert the dataset into feature vectors

import pandas as pd
from sklearn.preprocessing import StandardScaler

# Remove unnecessary column
df = df.drop(columns=["customerID"])

# Convert TotalCharges to numeric and handle missing values
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")
df["TotalCharges"] = df["TotalCharges"].fillna(df["TotalCharges"].median())

# Encode the target variable
df["Churn"] = df["Churn"].map({"Yes": 1, "No": 0})

# Encode binary Yes/No variables (except gender)
binary_cols = ["Partner","Dependents","PhoneService",
               "OnlineSecurity","OnlineBackup","DeviceProtection",
               "TechSupport","StreamingTV","StreamingMovies","PaperlessBilling"]

for col in binary_cols:
    df[col] = df[col].map({"Yes":1,"No":0})

# Handle gender separately (Male/Female)
df["gender"] = df["gender"].map({"Female":0, "Male":1})

# Apply One-Hot Encoding for categorical variables with multiple categories
multi_cat_cols = ["MultipleLines","InternetService","Contract","PaymentMethod"]
df = pd.get_dummies(df, columns=multi_cat_cols, drop_first=True)

# Normalize numerical features
numeric_cols = ["SeniorCitizen","tenure","MonthlyCharges","TotalCharges"]
scaler = StandardScaler()
df[numeric_cols] = scaler.fit_transform(df[numeric_cols])

# Split into feature vectors X and target variable y
X = df.drop(columns=["Churn"])
y = df["Churn"]

print("Shape X:", X.shape)
print("Shape y:", y.shape)
X.head()

import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style="whitegrid")

# Split the dataset based on churn value
df_churn0 = df[df["Churn"] == 0]
df_churn1 = df[df["Churn"] == 1]

# Get the list of feature columns (excluding the target column)
feature_cols = [col for col in df.columns if col != "Churn"]

for col in feature_cols:
    plt.figure(figsize=(8,5))

    # Check if the feature is categorical (few unique values)
    if df[col].nunique() <= 10:
        # Calculate the percentage proportion for each churn group
        prop0 = df_churn0[col].value_counts(normalize=True).reset_index()
        prop0.columns = [col, "proportion"]
        prop0["Churn"] = 0

        prop1 = df_churn1[col].value_counts(normalize=True).reset_index()
        prop1.columns = [col, "proportion"]
        prop1["Churn"] = 1

        # Combine the two groups into one dataframe
        prop_df = pd.concat([prop0, prop1])

        # Plot bar chart for categorical variables
        sns.barplot(x=col, y="proportion", hue="Churn", data=prop_df, palette="Set2")
        plt.ylabel("Rate (%)")

    else:
        # Plot KDE distribution for continuous variables
        sns.kdeplot(data=df_churn0, x=col, fill=True, label="Churn=0", alpha=0.4, color="blue")
        sns.kdeplot(data=df_churn1, x=col, fill=True, label="Churn=1", alpha=0.4, color="red")
        plt.ylabel("Probability Density")
        plt.legend()

    # Add chart title
    plt.title(f"Probability Distribution of {col} by Churn")
    plt.tight_layout()
    plt.show()